config/routes.rb
VideospielDatenbank::Application.routes.draw do

  resources :users do
    member do
      get :owned_games
    end
  end

  resources :games do
    member do
      get :owners
    end
    resources :reviews
  end

  get "ratings/:id" => "ratings#ding", as: "rating"
  post "ratings" => "ratings#create_and_update"   #match "ratings" => "ratings#create_and_update", :via => :post
  put "ratings/:id" => "ratings#create_and_update"   #match "ratings/:id" => "ratings#create_and_update", :via => :put


  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  
  match '/signup',  to: 'users#new'                         #get "signup" => "users#new", as: "signup"
  match '/signin',  to: 'sessions#new'                      #get "signin" => "sessions#new", as: "signin"
  match '/signout', to: 'sessions#destroy', via: :delete    #delete "signout" => "sessions#destroy", as: "signout"
  
  root to: 'pages#home'
  get "help" => "pages#help"
  get "about", to: "pages#about", as: "about"
 
end

app/views/misc/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/misc/_game_form.html.erb
<%= form_for(@game, :html => { :class => 'form-horizontal', :multipart => true}) do |f| %>

<%= render 'misc/error_messages', object: f.object %> 

  <div class="control-group">
    <%= f.label :cover, class: "control-label"%>
    <div class="controls"><%= f.file_field :cover %></div>
  </div>

  <div class="control-group">
    <%= f.label :title, class: "control-label"%>
    <div class="controls"><%= f.text_field :title %></div>
  </div>
  
  <div class="control-group">
    <%= f.label :subtitle, class: "control-label" %>
    <div class="controls"><%= f.text_field :subtitle %> </div>
  </div>
  
  <div class="control-group">
    <%= f.label :title_org, class: "control-label" %>
    <div class="controls"><%= f.text_field :title_org %> </div>
  </div>
  
  <div class="control-group">
    <%= f.label :subtitle_org, class: "control-label" %>
    <div class="controls"><%= f.text_field :subtitle_org %> </div>
  </div>
  
  <div class="control-group">
    <%= f.label :developer, class: "control-label" %>
    <div class="controls"><%= f.text_field :developer %></div>
  </div>
  
  <div class="control-group">
    <%= f.label :publisher, class: "control-label" %>
    <div class="controls"><%= f.text_field :publisher %></div>
  </div>
  
  <div class="control-group">
    <%= f.label :release, class: "control-label" %>
    <div class="controls date_field"><%= f.date_select :release, 
    									start_year: Time.now.year - 100,
    									end_year: Time.now.year  %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :system, class: "control-label" %>
    <div class="controls"><%= f.text_field :system %> </div>
  </div>
  
  <div class="control-group">
    <%= f.label :genre, class: "control-label" %>
    <div class="controls"><%= f.text_field :genre %> </div>
  </div>
  
  <div class="control-group">
    <%= f.label :usk, class: "control-label" %>
    <div class="controls"><%= f.text_field :usk %> </div>
  </div>
  
  <div class="control-group">
    <%= f.label :medium, class: "control-label" %>
    <div class="controls"><%= f.text_field :medium %> </div>
  </div>
  
  <div class="control-group">
    <%= f.label :indizierung, class: "control-label" %>
    <div class="controls"><%= f.check_box :indizierung %> </div>
  </div>
  
    <%= f.submit "Spiel anlegen", class: "btn btn-large btn-primary controls"%>
  
<% end %>

app/views/misc/_game_users.html.erb
  Im Besitz von </br>
 <a href="<%= owners_game_path(@user) %>">
    <strong class="own_stats">
       <%= pluralize(@game.owners.count, "User", "Usern") %>
    </strong>
 </a>
  

app/views/misc/_own_game_form.html.erb
  <div id="own_game_form">
  <% if current_user.owning?(@game) %>
    <%= render 'discard_game' %>
  <% else %>
    <%= render 'own_game' %>
  <% end %>
  </div>

app/views/misc/_search_results.html.erb
<% if(params[:search]) %>
	<table>
	<% @games.each do |game| %>
	  <tr>
	    <td><%= link_to game.title, game %> 
	    	<span>(<%= game.release.strftime("%Y") %>)</span>
	    </td>
	    
	    <td><%= link_to 'Löschen', game, method: :delete, data: { confirm: "Sicher?"} %></td>
	    
	  </tr>
	<% end %>
	</table>
<% else %>
	<i>Keine Einträge gefunden...</i>
<% end %>

app/views/misc/_user_games.html.erb
<% @user ||= current_user %>

<div class="stats">
  <a href="<%= owned_games_user_path(@game) %>">   <!-- following_user_path-->
    <strong>
      <%= pluralize(@user.owned_games.count, "Spiel", "Spiele") %> im Besitz
      
    </strong>
    
  </a>
</div>