config/routes.rb
VideospielDatenbank::Application.routes.draw do

  resources :users do
    member do
      get :owned_games
    end
  end

  resources :games do
    member do
      get :owners
    end
    resources :reviews
  end

  get "ratings/:id" => "ratings#ding", as: "rating"
  post "ratings" => "ratings#create_and_update"   #match "ratings" => "ratings#create_and_update", :via => :post
  put "ratings/:id" => "ratings#create_and_update"   #match "ratings/:id" => "ratings#create_and_update", :via => :put


  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  
  match '/signup',  to: 'users#new'                         #get "signup" => "users#new", as: "signup"
  match '/signin',  to: 'sessions#new'                      #get "signin" => "sessions#new", as: "signin"
  match '/signout', to: 'sessions#destroy', via: :delete    #delete "signout" => "sessions#destroy", as: "signout"
  
  root to: 'pages#home'
  get "help" => "pages#help"
  get "about", to: "pages#about", as: "about"
 
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController  
  before_filter :require_login, only: [:new, :create, :destroy]
  before_filter :correct_user,   only: :destroy
  
  def index
    
  end
  
  def create
    @game = Game.find_by_id(params[:game_id]) #nur :id funktioniert nicht
    @review = current_user.reviews.build(params[:review])
    @review.game_id = @game.id
    @review.user_id = current_user.id       
    
    if @review.save
      flash[:success] = "review created!"
      redirect_to game_path(@game)
    else
      render 'new'
    end
  end

  def new
    @review = Review.new
    #@game = Game.find_by_id(params[:game_id])
    #@review.game_id = @game.id
  end
  
  def show
    @review = Review.find_by_game_id(params[:game_id], params[:id])
  end
  
  def destroy
    Review.find(params[:id]).destroy
    @game = Game.find_by_id(params[:game_id])
    flash[:success] = "Review erased"
    redirect_to game_path(@game)
  end
  
  private

    def correct_user
      @review = current_user.reviews.find_by_id(params[:id])
      redirect_to root_url if @review.nil?
    end
  
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_game_review.html.erb
<li id="<%= game_review.id %>">
	
  <%= link_to gravatar_for(game_review.user), game_review.user %>

  <span> <%= link_to game_review.user.name, game_review_path(@game, game_review) %> </span>
  </br>
  <span class="timestamp">
    Posted <%= time_ago_in_words(game_review.created_at) %> ago.
  </span>
  
    <% if current_user?(game_review.user) %>
    <%= link_to "delete", game_review_path(@game, game_review), method: :delete,
                                  data: { confirm: "You sure?" } %>
  	<% end %>
  
</li>

app/views/reviews/_review_area.html.erb
	<h3>Reviews</h3>

	<% if user_signed_in? %>
    	
		<div class="user_review">
	  		<%= link_to "Kritik verfassen", new_game_review_path(@game), class: "btn btn-large btn-primary" %>
		</div>
	<% end %>
	
	<% if @reviews.any? %>
  		<ol class="reviews">
    		<%= render partial: 'reviews/game_review', collection: @reviews %>
  		</ol>
  		<%= will_paginate @reviews %>
	<% end %>

app/views/reviews/_user_review.html.erb
<li id="<%= user_review.id %>">
	
  <%= link_to user_review.game.title, user_review.game %>

  <span class="review_delete">    
  	(<% if current_user?(user_review.user) %>
    <%= link_to "delete", game_review_path(@user, user_review), method: :delete,
                                     data: { confirm: "You sure?" } %>
  	<% end %>)
  </span>
  
  <span class="timestamp">
    Posted <%= time_ago_in_words(user_review.created_at) %> ago.
  </span>

  
</li>
  

app/views/reviews/new.html.erb
<% provide(:title, "Neues Review") %>

<h1>Reviews#new</h1>

<%= form_for(@review, :url => game_reviews_path) do |f| %>
  <%= render 'misc/error_messages', object: f.object %>
  
  <div class="field review_text_area">
    <%= f.text_area :content, placeholder: "Compose new review..." %>
  </div>
  
  <!--%= hidden_field_tag("game_id", @game.id) %-->

  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/reviews/show.html.erb
<p class="review_info">  
	<b>Review</b> zu <%= link_to @review.game.title, @review.game %> </br>
	von <%= link_to @review.user.name, @review.user %>
	
</p>
<p class="review_text">
  <%= @review.content %>
</p>