config/routes.rb
VideospielDatenbank::Application.routes.draw do

  resources :users do
    member do
      get :owned_games
    end
  end

  resources :games do
    member do
      get :owners
    end
    resources :reviews
  end

  get "ratings/:id" => "ratings#ding", as: "rating"
  post "ratings" => "ratings#create_and_update"   #match "ratings" => "ratings#create_and_update", :via => :post
  put "ratings/:id" => "ratings#create_and_update"   #match "ratings/:id" => "ratings#create_and_update", :via => :put


  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  
  match '/signup',  to: 'users#new'                         #get "signup" => "users#new", as: "signup"
  match '/signin',  to: 'sessions#new'                      #get "signin" => "sessions#new", as: "signin"
  match '/signout', to: 'sessions#destroy', via: :delete    #delete "signout" => "sessions#destroy", as: "signout"
  
  root to: 'pages#home'
  get "help" => "pages#help"
  get "about", to: "pages#about", as: "about"
 
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  


		<div class="row-fluid">
			<div class="span6 ding1">
				<a href="http://jayzvgquiz.de/">Videogame Quiz</a>
				by Sir Jay
			</div>
			<div class="span6 ding2">

						<a href="http://ofdb.de">Movies</a>
	
			</div>
		</div>


</footer>

app/views/layouts/_header.html.erb
<header class="navbar"> <!-- navbar-fixed-top--->
  <div class="navbar-inner">	  	
        <ul class="nav pull-right">
          <li><%= render 'pages/search_form'%></li>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "User-Center", users_path %></li>      	
        </ul>     
  </div>
</header>

app/views/layouts/_sidebar_user.html.erb
<ul class="nav">
  <% if user_signed_in? %>
    <li class="login_state">Eingeloggt als 
    </li>
    <li id="fat-menu" class="dropdown">
      <a href="#" class="dropdown-toggle login_state" data-toggle="dropdown">
        <span class="user_name"><%= current_user.name%></span> <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to "Profil", user_path(current_user) %></li>
        <li><%= link_to "Bearbeiten", edit_user_path(current_user) %></li>
        <li class="divider"></li>
        <li>
          <%= link_to "Logout", signout_path, method: "delete" %>
        </li>
      </ul>
    </li>
    
  <% else %>
  	<p class="login_state">Du bist noch nicht angemeldet</p>
  	<li><%= link_to "Login", signin_path, class: "btn_login btn" %></li>
  	<li><%= link_to "Registrieren", signup_path, class: "btn" %></li>
  <% end %>
  

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>GameHawks | <%= yield(:title) %></title>  
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	  <!--%= yield :script %-->
	</head>
	
	<body>
	
		<%= render "layouts/header"%>
		<div id="background_1">
			<div class="background_2"></div>
				
		    <div class="content">
			    <div class="row-fluid">
					  <% flash.each do |key, value| %>
				        <div class="alert alert-<%= key %>"><%= value %></div>
				      <% end %>
				      
				      <div class="span10 main-container">
				      	<%= yield %>
				      	
				      </div>
				      
				      <div class="span2 sidebar"> 
				      	<%= render "layouts/sidebar_user"%> 
				      	<%= yield(:sidebar)%>
				      </div>
			      </div>
		    </div>
		    
		    
	  </div>
	<%= render 'layouts/footer' %>
	</body>
</html>